### PR TITLE
Absolute config paths

### LINKED ISSUE #6: Absolute paths for config files
Hi,
I really like your extension as it made my life easier.

One of the things that would be great would be support for absolute paths of config files. Currently I have nested test suite with different config files and navigating to those files makes things messy.

In `NetteDiModule::createContainer` we can check whether `$file` is absolute path and prepend path only if it isn't.

What do you think? I can prepare PR if you think it's worth it. :slightly_smiling_face: 

```
$configFiles = is_array($this->configFiles) ? $this->configFiles : $this->config['configFiles'];
foreach ($configFiles as $file) {
    $configurator->addConfig($this->path.'/'.$file);
}
```

### PR DESCRIPTION
**Pull request by fmasa**
I also added nette/utils as direct dependency to composer.json as it's used thorough NetteDIModule but not explicitly listed as dependency.

Closes #6

### CODE REVIEW

**Comment by enumag** [comment]
Remind me... it is absolute from project root? Can you mention it in the docs?

**Comment by fmasa** [comment]
Right now all paths must be relative to tests root. This allows code like this:
```php
$ŧhis->tester->useConfigFiles([__DIR__ . '/config.neon']);
```

I'll update the docs.

**Comment by enumag** [comment]
ping @fmasa

**Comment by fmasa** [comment]
Thanks for following up, this PR slipped my mind. I added the note about usage to docs.

**Comment by enumag** [comment]
@fmasa Thank you!

**Pull request merged**
